### ISSUE TITLE
"Set background as transparent" seems to be invalid

### ISSUE THREAD

**Issue by StarHeartHunt** [paissaheavyindustries/Triggernometry#99]
![image](https://github.com/paissaheavyindustries/Triggernometry/assets/14922941/8d82e4ab-eae1-4a32-be7c-e2188681c359)

To reproduce: 

1. Create a new trigger and add a text aura operation action
2. Set the background as transparent and get a black bg

**Comment by StarHeartHunt** [comment]
Maybe related to sharpdx/SharpDX#1107

**Comment by yjywybb** [comment]
same issue

**Comment by paissaheavyindustries** [comment]
should be fixed

**Comment by StarHeartHunt** [comment]
it seems the issue still exists with 1.2.0.6, maybe related to the Windows update, i am using Windows 11 24H2
